# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 21:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('race', models.CharField(choices=[('Norn', 'Norn'), ('Asura', 'Asura'), ('Sylvary', 'Sylvary'), ('Charr', 'Charr'), ('Human', 'Human')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)])),
                ('guild', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('profession_type', models.CharField(choices=[('Guardian', 'Guardian'), ('Mesmer', 'Mesmer'), ('Warrior', 'Warrior'), ('Necromancer', 'Necromancer'), ('Revenant', 'Revenant'), ('Ranger', 'Ranger'), ('Engineer', 'Engineer'), ('Elementalist', 'Elementalist'), ('Thief', 'Thief')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw2_app.Profession'),
        ),
    ]
