# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 10:09
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('race', models.CharField(choices=[('Norn', 'Norn'), ('Asura', 'Asura'), ('Sylvary', 'Sylvary'), ('Charr', 'Charr'), ('Human', 'Human')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)])),
                ('guild', models.CharField(blank=True, max_length=50)),
                ('profession_type', models.CharField(choices=[('Thief', 'Thief'), ('Guardian', 'Guardian'), ('Mesmer', 'Mesmer'), ('Warrior', 'Warrior'), ('Necromancer', 'Necromancer'), ('Revenant', 'Revenant'), ('Ranger', 'Ranger'), ('Engineer', 'Engineer'), ('Elementalist', 'Elementalist')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playerprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAchievement',
            fields=[
                ('achievement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gw2_app.Achievement')),
                ('type', models.CharField(choices=[('PvE', 'Player vs Enviromnent'), ('PvP', 'Player vs Player'), ('Fractal', 'Fractal')], max_length=10, null=True)),
            ],
            bases=('gw2_app.achievement',),
        ),
        migrations.CreateModel(
            name='GeneralAchievement',
            fields=[
                ('achievement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gw2_app.Achievement')),
                ('requirements', models.TextField(null=True)),
            ],
            bases=('gw2_app.achievement',),
        ),
        migrations.CreateModel(
            name='PveMode',
            fields=[
                ('gamemode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='gw2_app.GameMode')),
                ('pve_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('gw2_app.gamemode',),
        ),
        migrations.CreateModel(
            name='PvpMode',
            fields=[
                ('gamemode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='gw2_app.GameMode')),
                ('pvp_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('gw2_app.gamemode',),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='player',
            field=models.ManyToManyField(to='gw2_app.PlayerProfile'),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gw2_app.PlayerProfile'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gw2_app.PlayerProfile'),
        ),
        migrations.CreateModel(
            name='PveEvent',
            fields=[
                ('pvemode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gw2_app.PveMode')),
                ('event_name', models.CharField(max_length=20, null=True)),
                ('event_boss_name', models.CharField(max_length=20, null=True)),
                ('event_hardcore_boss_name', models.CharField(blank=True, max_length=20, null=True)),
                ('event_time', models.TimeField()),
            ],
            bases=('gw2_app.pvemode',),
        ),
        migrations.CreateModel(
            name='PvePersonalStory',
            fields=[
                ('pvemode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gw2_app.PveMode')),
                ('current_story_step_name', models.CharField(max_length=30, null=True)),
                ('current_story_objective', models.CharField(max_length=50, null=True)),
                ('current_story_description', models.TextField(null=True)),
            ],
            bases=('gw2_app.pvemode',),
        ),
        migrations.CreateModel(
            name='StructuredPvpStat',
            fields=[
                ('pvpmode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gw2_app.PvpMode')),
                ('ranking', models.IntegerField(null=True)),
                ('win_lose_ratio', models.IntegerField(null=True)),
                ('league', models.CharField(max_length=20, null=True)),
            ],
            bases=('gw2_app.pvpmode',),
        ),
        migrations.CreateModel(
            name='WvwStat',
            fields=[
                ('pvpmode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gw2_app.PvpMode')),
                ('objective_name', models.CharField(max_length=20, null=True)),
                ('objective_sector', models.CharField(max_length=20, null=True)),
                ('objective_map', models.CharField(max_length=20, null=True)),
                ('time_start', models.TimeField(null=True)),
                ('time_end', models.TimeField(null=True)),
            ],
            bases=('gw2_app.pvpmode',),
        ),
    ]
