# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pveevent',
            name='event_description',
        ),
        migrations.AddField(
            model_name='pveevent',
            name='event_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
